# Generated by Django 5.0.6 on 2024-11-18 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAPP', '0012_featureproject_project_alter_donation_project_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
