# Generated by Django 5.0.6 on 2024-11-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAPP', '0016_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phn_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
