# Generated by Django 5.0.6 on 2024-11-23 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAPP', '0018_profile_is_signup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='HomeAPP.profile'),
        ),
        migrations.AddField(
            model_name='project',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='HomeAPP.profile'),
        ),
    ]
