# Generated by Django 5.0.6 on 2024-11-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAPP', '0019_donation_profile_project_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='title',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
