# Generated by Django 5.0.6 on 2024-11-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAPP', '0025_alter_project_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
